import { APP_CONFIG } from '@/constants/config';

/**
 * Standard HTTP Fetch Client wrapper with async network latency mockup
 */
export async function apiClient(endpoint, options = {}) {
  const url = `${APP_CONFIG.API_BASE_URL}${endpoint}`;
  
  const headers = {
    'Content-Type': 'application/json',
    ...options.headers,
  };

  const token = localStorage.getItem(APP_CONFIG.LOCAL_STORAGE_TOKEN_KEY);
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const config = {
    ...options,
    headers,
  };

  // Simulate network latency (800ms)
  await new Promise((resolve) => setTimeout(resolve, 800));

  // Live Fetch implementation:
  // const response = await fetch(url, config);
  // if (!response.ok) {
  //   const errorData = await response.json().catch(() => ({}));
  //   throw new Error(errorData.message || `Request failed with status ${response.status}`);
  // }
  // return response.json();

  return { success: true, message: "Mock response generated by Client" };
}

export default apiClient;
